# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
---
version: "3"

services:  
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9001:9001
      - 9000:9000
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    command: ["server", "/data", "--console-address", ":9001"]
    networks:
      iceberg_net:
        aliases:
          - warehouse.minio
  
  mc:
    image: minio/mc
    container_name: mc
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    networks:
      - iceberg_net
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc policy set public minio/warehouse;
      tail -f /dev/null
      "
    depends_on:
      - minio
  
  rest:
    image: tabulario/iceberg-rest
    container_name: iceberg-rest
    ports:
      - 8181:8181
    networks:
      - iceberg_net
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000

  spark-iceberg:
    image: tyler/spark-iceberg
    container_name: spark-iceberg
    build: spark-iceberg/
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    volumes:
      - ./projects:/src/projects
      - ./data:/src/data
    ports:
      - 4040:4040 # Spark UI Port
      - 7077:7077 # Spark port
      - 8080:8080 # Spark driver UI
      - 8888:8888 # Spark notebook port
      - 10000:10000 # Thrift ODBC/JDBC port
      - 10001:10001 # Thrift ODBC/JDBC port
      - 18080:18080 # Spark history web ui port
    networks:
      iceberg_net:
        aliases:
          - warehouse.minio
          - dbt
          - spark-iceberg
          - spark
    depends_on:
      - rest
      - minio
  
  trino:
    image: 'trinodb/trino:latest'
    container_name: trino
    ports:
      - '8060:8060'
    volumes:
      - ./trino/etc:/etc/trino
    networks:
      - iceberg_net

networks:
  iceberg_net:
    driver: bridge
