dbt_iceberg:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      schema: dbt
      host: 127.0.0.1
      port: 10000
      threads: 1
      connect_retries: 3
      connect_timeout: 15
      retry_all: true