dbt_iceberg:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      schema: analytics
      port: 10009
      threads: 1
      connect_retries: 5
      connect_timeout: 60
      retry_all: true